# 指定运行端口
server:
  port: 8888



# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlearn?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    username: onlearn
    password:

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: input
  configuration:
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

comm:
  property: weixin